---

- name: Assert 'android_sdk_home' variable
  ansible.builtin.assert:
    that:
      - android_sdk_home is defined
      - android_sdk_home is string
      - android_sdk_home | length > 0

- name: Assert 'android_sdk_bin' variable
  ansible.builtin.assert:
    that:
      - android_sdk_bin is defined
      - android_sdk_bin is string
      - android_sdk_bin | length > 0


- name: Assert 'android_user_home' variable
  ansible.builtin.assert:
    that:
      - android_user_home is defined
      - android_user_home is string
      - android_user_home | length > 0


- name: Assert 'android_emulator_home' variable
  ansible.builtin.assert:
    that:
      - android_emulator_home is defined
      - android_emulator_home is string
      - android_emulator_home | length > 0


- name: Assert 'android_avd_home' variable
  ansible.builtin.assert:
    that: 
      - android_avd_home is defined
      - android_avd_home is string
      - android_avd_home | length > 0


- name: Assert 'android_adb_to_path' variable
  ansible.builtin.assert:
    that:
      - android_adb_to_path is boolean
  when:
    - android_adb_to_path is defined


- name: Assert 'android_sdkmanager_to_path' variable
  ansible.builtin.assert:
    that:
      - android_sdkmanager_to_path is boolean
  when:
    - android_sdkmanager_to_path is defined


- name: Assert 'android_cmdlinetools_bootstrap_build' variable
  ansible.builtin.assert:
    that: 
      - android_cmdlinetools_bootstrap_build is defined
      - android_cmdlinetools_bootstrap_build is integer


- name: Assert 'android_cmdlinetools_bootstrap_checksum' variable
  ansible.builtin.assert:
    that: 
      - android_cmdlinetools_bootstrap_checksum is defined
      - android_cmdlinetools_bootstrap_checksum is string
      - android_cmdlinetools_bootstrap_checksum | length > 0
    fail_msg: "Checksum for cmdline bootstrap is required. Find it at https://developer.android.com/studio#command-tools"
    

- name: Assert 'android_requested_sdk' variable
  ansible.builtin.assert:
    that: 
      - android_requested_sdk is mapping
  when:
    - android_requested_sdk is defined


- name: Validate 'android_requested_sdk' schema
  ansible.utils.validate:
    data: "{{ android_requested_sdk }}"
    criteria:
      - "{{ lookup('file',  './criteria/requested_sdk_criteria.json') | from_json }}"
    engine: ansible.utils.jsonschema
  when:
  - android_requested_sdk is defined
